/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./subHeader";
import RegisterForm from "./RegisterForm";

function MyComponent() {
  return (
    <div className="flex flex-col">
      <Header />
      <section className="flex flex-col justify-center items-center px-20 py-28 mt-6 w-full border border-t max-md:px-5 max-md:py-24 max-md:max-w-full">
        <RegisterForm />
      </section>
    </div>
  );
}

export default MyComponent;
