/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className=" flex flex-col  items-center gap-1.5 s text-xs tracking-tight">
   <nav className="flex mt-5 gap-1 flex-row w-full text-xs max-w-[1363px] items-start max-md:max-w-full">
        <span className=" text-gray-400">Home</span>
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/0846c7aa25351fb225629f8c53603a84f1c8a30df192fcb2fd2d31a25cb5bebe?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc" className="object-contain shrink-0 self-start w-3 aspect-square" alt="" />
        <span className="text-gray-950">My account</span>
      </nav>
    </header>
  );
}

export default Header;
