/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function Button({ children }) {
  return (
    <button className="px-12 py-4 mt-6 text-sm font-bold tracking-tight leading-3 text-center text-white bg-purple-800 rounded-lg w-full max-md:px-5 max-md:max-w-full">
      {children}
    </button>
  );
}

export default Button;