/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function Checkbox({ label }) {
  const id = label.toLowerCase().replace(/\s+/g, '-');
  return (
    <div className="flex flex-1 gap-2.5 text-xs text-gray-950">
      <input
        type="checkbox"
        id={id}
        className="shrink-0 w-4 h-4 bg-white rounded border border-gray-300 border-solid shadow-[0px_1px_2px_rgba(0,0,0,0.047)]"
      />
      <label htmlFor={id} className="my-auto">{label}</label>
    </div>
  );
}

export default Checkbox;