/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function InputField({ label, type = 'text', required = false }) {
  const id = label.toLowerCase().replace(/\s+/g, '-');
  return (
    <div className="mb-5">
      <label htmlFor={id} className="block mb-2 text-sm text-gray-950">
        {label} {required && '*'}
      </label>
      <input
        type={type}
        id={id}
        className="flex shrink-0 w-full bg-white rounded-lg border border-gray-300 border-solid h-[42px] shadow-[0px_1px_2px_rgba(0,0,0,0.047)]"
        required={required}
      />
    </div>
  );
}

export default InputField;