/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import InputField from './InputField';
import Button from './Button';
import Checkbox from './Checkbox';
import { userState } from '../Context';
function LoginPage()  {
  const { setuserExist} = userState();
  return (
    <main className="flex flex-col items-center tracking-tight">
      <nav className="flex mt-5 gap-1 flex-row w-full text-xs max-w-[1363px] items-start max-md:max-w-full">
        <span className=" text-gray-400">Home</span>
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/0846c7aa25351fb225629f8c53603a84f1c8a30df192fcb2fd2d31a25cb5bebe?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc" className="object-contain shrink-0 self-start w-3 aspect-square" alt="" />
        <span className="text-gray-950">My account</span>
      </nav>
      <section className="flex flex-col items-center px-20 pt-28 pb-80 mt-6 w-full border border-t max-md:px-5 max-md:py-24 max-md:max-w-full">
        <div className="flex flex-col -mb-16 max-w-full w-[470px] max-md:mb-2.5">
          <div className="flex gap-8 self-center max-w-full text-3xl font-semibold whitespace-nowrap w-[209px]">
            <h1 className="text-gray-900">Login</h1>
            <span onClick={()=>{setuserExist(false)}} className="grow shrink cursor-pointer text-gray-400 w-[94px]">Register</span>
          </div>
          <p className="self-center mt-10 text-sm text-center text-gray-950">
            If you have an account, sign in with your username or email address.
          </p>
          <form>
            <InputField label="Username or email address" required />
            <InputField label="Password" type="password" required />
            <div className="flex gap-10 mt-4 w-full max-md:max-w-full">
              <Checkbox label="Remember me" />
              <a href="#" className="text-sm text-blue-700">Lost your password?</a>
            </div>
            <Button>Log in</Button>
          </form>
        </div>
      </section>
    </main>
  );
}

export default LoginPage;