/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function IconComponent() {
  return (
    <div className="flex overflow-hidden flex-col w-12  max-w-[24px]">
      <img 
        loading="lazy" 
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c8db10994bd91812403737a956860a0f6523dd2b220d1cc2a0040d2d53ceb856?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc" 
        className="object-contain  w-full aspect-[1.14]" 
        alt="Icon"
      />
    </div>
  );
}

export default IconComponent;