/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function ImageComponent() {
  return (
    <div className="flex overflow-hidden w-20 flex-col max-w-[24px]">
      <img 
        loading="lazy" 
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c177390617b7bb6adbb4dc536c1f642743427b487bd3c9a749a9e6415f47259c?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc" 
        className="object-contain w-full aspect-[1.2]" 
        alt=""
      />
    </div>
  );
}

export default ImageComponent;