/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";
import IconComponent from "./IconComponent";
import ImageComponent from "./ImageComponent";
import SubHeader from "../main/subHeader";
const MainHeader = () => {
  return (
    <div className="flex z-10 flex-col justify-between items-center px-16 py-4 w-full bg-white border border border-solid max-md:px-5 max-md:max-w-full">
      
      <div className="flex  gap-4  flex-row w-full max-w-[1363px] max-md:max-w-full">
       
        <div className="flex gap-2.5 self-start text-2xl font-bold text-black whitespace-nowrap">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/5921eaba5f0947e3ea9af79b4b128da403f89cacf551d49377d6513a5095fb44?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc"
            className="object-contain shrink-0 rounded-none aspect-[1.15] w-[45px]"
            alt="JinStore Logo"
          />
          <div>JinStore</div>
        </div>
        <SearchBar />
        <div className="flex gap-3.5 my-auto tracking-tight leading-tight text-gray-950">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e82da8c5ffe7078e28dde2f55ffebc7884c88d141b901b870c20e641ac5f60b7?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc"
            className="object-contain shrink-0 aspect-square w-[26px]"
            alt=""
          />
          <div className="flex flex-col self-start">
            <div className="self-start text-xs">Sign In</div>
            <div className="text-sm font-medium">Account</div>
          </div>
        </div>
        <div className="flex gap-5 self-start mt-1.5 text-xs font-semibold tracking-tight leading-relaxed text-red-50 whitespace-nowrap">
         <div className="relative flex">
         <div className="px-1.5 bg-red-600 relative bottom-1 left-7 rounded-lg h-[17px] w-[17px]">
            
            0
          </div>
         <IconComponent  />
        
         </div>
         <div className="relative flex">
         <div className="px-1.5 bg-red-600 relative bottom-1 left-7 rounded-lg h-[17px] w-[17px]">
            
            0
          </div>
         <ImageComponent />
        
         </div>
      
        
        </div>
        
      </div>
      
    </div>
  );
};

export default MainHeader;
