/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SubHeader from "../main/subHeader";
const Navigation = () => {
  return (
    <nav className="flex flex-col justify-center items-center px-16 py-px w-full tracking-tight bg-white max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between w-full max-w-[1360px] max-md:max-w-full">
        <div className="flex flex-wrap gap-6 text-base font-semibold leading-3 text-gray-950">
          <div className="flex gap-2 whitespace-nowrap">
            <a href="/" className="my-auto">
              Home
            </a>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/4f54211b87b757df091a32f02e9c8e6073293a05913f521392d68b185fe3098c?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc"
              className="object-contain shrink-0 w-2.5 aspect-[0.21]"
              alt=""
            />
          </div>
          <div className="flex gap-2.5 whitespace-nowrap">
            <a href="/shop" className="my-auto">
              Shop
            </a>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3935e3e5eef9494173727418f567f5ff3d3cffa6098affb8037ee401a0a8d75e?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc"
              className="object-contain shrink-0 aspect-[0.19] w-[9px]"
              alt=""
            />
          </div>
          <div className="flex gap-7 my-auto">
            <a href="/fruits-vegetables" className="grow">
              Fruits & Vegetables
            </a>
            <a href="/beverages">Beverages</a>
            <a href="/blog">Blog</a>
            <a href="/contact">Contact</a>
          </div>
        </div>
        <div className="flex gap-6">
          <div className="flex gap-3 text-base font-semibold leading-3 text-gray-950">
            <a href="/trending" className="grow my-auto">
              Trending Products
            </a>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/70d4ef10b604660f3a2a966f1132a4d27adde36529d681599bcc57902cc85142?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc"
              className="object-contain shrink-0 w-2.5 aspect-[0.21]"
              alt=""
            />
          </div>
          <div className="flex gap-2.5 items-center">
            <div className="grow self-stretch my-auto text-base font-semibold leading-3 text-red-600">
              Almost Finished
            </div>
            <div className="self-stretch px-2 py-1.5 my-auto text-xs font-bold leading-none text-center text-white whitespace-nowrap rounded">
              SALE
            </div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d196bfa1078a34f184248680f2682a4193081b86a8dcfe6669b4680d68bc443b?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc"
              className="object-contain shrink-0 self-stretch w-2.5 aspect-[0.21]"
              alt=""
            />
          </div>
        </div>
        
      </div>
     
    </nav>
  );
};

export default Navigation;
