/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchBar = () => {
  return (
    <div className=" ml-10 flex w-full gap-3.5 items-center">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/3ceda50612f23f5606af89227c86f6e8e144db1abe2fdf293919e5bf1640f442?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc"
        className="object-contain shrink-0 self-stretch my-auto aspect-square w-[28px]"
        alt=""
      />
      <div className="flex flex-col gap-0 w-16 self-stretch my-auto tracking-tight leading-tight text-gray-950">
        <div className="text-xs w-full">Deliver to</div>
        <div className="self-start mt-1.5 text-sm font-medium">all</div>
      </div>
      <form className="flex w-full  gap-4 self-stretch py-2.5 pr-2.5 pl-5 text-sm tracking-tight text-gray-500 bg-gray-100 rounded-lg max-md:max-w-full">
  <input className="form-control w-full" type="text" placeholder="Search for products , catagories and brands ..." />
        <button type="submit" aria-label="Search">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7c99612328cf47d0f6fed71239eb732830f9c8faa07e9ed9b4a72a82fc0eae6b?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc"
            className="object-contain shrink-0 aspect-square w-[26px]"
            alt=""
          />
        </button>
      </form>
    </div>
  );
};

export default SearchBar;
