/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TopBar = () => {
  return (
    <header className="flex flex-col justify-center items-center px-16 py-3.5 w-full text-xs font-medium tracking-tight text-gray-500 bg-white border border-b max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between w-full max-w-[1359px] max-md:max-w-full">
        <nav className="flex flex-wrap   gap-3">
         <div className="flex flex-row sm:justify-center gap-2">
         <a href="#about" className="my-auto">
            About Us
          </a>
          <a href="#account" className="my-auto">My account</a>
          <a href="#wishlist" className="my-auto">
            Wishlist
          </a>
         </div>
          <div className="px-4 py-0.5 border border-l">
            We deliver to you every day from{" "}
            <span className="font-bold text-orange-600">7:00 to 23:00</span>
          </div>
        </nav>
        <div className="flex gap-2 my-auto">
          <div className="grow">English</div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b307b100114cdbeb237ae47632a106f83a4cb3e19fcd6a314a9d75d8e3da4e6?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc"
            className="object-contain shrink-0 self-start w-2 aspect-[0.8]"
            alt=""
          />
          <div>USD</div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/3f8d5a5f700036f1ccd79c9b07fe4bad74b5eb0615fcfb358d301918ffe1c594?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc"
            className="object-contain shrink-0 self-start w-2 aspect-[0.8]"
            alt=""
          />
          <a href="#tracking">Order Tracking</a>
        </div>
      </div>
    </header>
  );
};

export default TopBar;
