/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function AppDownload() {
  return (
    <div className="flex flex-col items-start">
      <h3 className="text-sm font-semibold tracking-tight leading-tight text-gray-900">
        Download our app
      </h3>
      <div className="flex gap-4 self-stretch mt-5 text-xs font-medium tracking-tight leading-4 text-gray-500">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/9db15f40994681e1ed22de4e58ffc8a8f3bdd911852362338b19f04adb5e8869?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc" alt="App Store" className="object-contain shrink-0 max-w-full aspect-[3.08] w-[120px]" />
        <p className="my-auto">
          Download App Get <br /> -10% Discount
        </p>
      </div>
      <div className="flex gap-4 self-stretch mt-2.5 text-xs font-medium tracking-tight leading-4 text-gray-500">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/51cd1383d33ca021e40dfc416d7bfbadf35f18266105d6b745471d01d9c5c6a7?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc" alt="Google Play" className="object-contain shrink-0 max-w-full aspect-[3.08] w-[120px]" />
        <p className="my-auto">
          Download App Get <br /> -20% Discount
        </p>
      </div>
    </div>
  );
}

export default AppDownload;