/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function HelpSection() {
  return (
    <section className="flex flex-col items-start">
      <h3 className="text-sm font-semibold tracking-tight leading-tight text-gray-900">
        Do You Need Help ?
      </h3>
      <p className="self-stretch mt-6 text-sm tracking-tight leading-5 text-gray-500">
        Autoseligen syr. Nek diarask fröbomba. Nör <br /> antipol kynoda nynat. Pressa fåmoska.
      </p>
      <div className="flex gap-6 mt-10">
        <div className="flex flex-col self-start">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/04a533459e26162d2fcffa2a4cbe75e3914c3fe31417a2278539fb07c99b3160?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc" alt="" className="object-contain w-7 aspect-square" />
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/598eb0be1bc89e8d8f16134b003eeb87dfcfe7a5aa8ad5a34215d1962d5faa10?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc" alt="" className="object-contain mt-14 w-7 aspect-square max-md:mt-10" />
        </div>
        <div className="flex flex-col text-xs tracking-tight text-gray-900">
          <p>Monday-Friday: 08am-9pm</p>
          <p className="mt-3 text-xl font-bold tracking-tighter max-md:mr-2">0 800 300-353</p>
          <p className="mt-11 max-md:mt-10 max-md:mr-0.5">Need help with your order?</p>
          <p className="self-start mt-2.5 text-sm font-semibold">info@example.com</p>
        </div>
      </div>
    </section>
  );
}

export default HelpSection;