/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const paymentMethods = [
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/5a4e4efca1c7f26cca89f2ce8b540bed8e2c98e3fd0ac1a350db756daae74821?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc", alt: "Visa", className: "w-9 aspect-[2.77]" },
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/4f95f763c422b9e0a26d09bda24687c9f99432a4ab1d050b708775540a7ea58d?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc", alt: "Mastercard", className: "w-6 aspect-[1.6]" },
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/efe3205356d741ca445723573e08a4d7f1cfd7b894f48c8f0659bbaff6496a63?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc", alt: "American Express", className: "aspect-[3.53] w-[53px]" },
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/f1db376ff89de9f17f03a904e5de9f64811aa4b247cd9f39f6f7802ece94ade2?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc", alt: "PayPal", className: "aspect-[2.73] w-[41px]" },
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/c5da2637ff158293013163c02a48843ce79c08e5e6a3156759091af7e1e9b4e4?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc", alt: "Discover", className: "w-16 aspect-[4.27]" }
];

function PaymentMethods() {
  return (
    <div className="flex gap-2.5 self-start mt-6">
      {paymentMethods.map((method, index) => (
        <img
          key={index}
          loading="lazy"
          src={method.src}
          alt={method.alt}
          className={`object-contain shrink-0 ${method.className}`}
        />
      ))}
    </div>
  );
}

export default PaymentMethods;