/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const socialIcons = [
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/33d01e5f3bf742743547f259b4f933c753d8fb80d417c722361fbdb21819947d?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc", alt: "Facebook" },
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/fdef6eddd7e08680c8bcbff0b70da3215165dfcccf88fc8ed4f2d4b293f38a4d?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc", alt: "Twitter" },
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/a3b5b8efcf79a57813972cb70cebd92e7c3256a7f013f1266484fa0377a6c2a2?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc", alt: "Instagram" },
  { src: "https://cdn.builder.io/api/v1/image/assets/TEMP/d4372aecfe1845027452c4e88d6b92c9db0c869b86a1f3caf4b10d95c0e2416c?placeholderIfAbsent=true&apiKey=f7a3dbf520784f20adb3c0751393b5fc", alt: "LinkedIn" }
];

function SocialMedia() {
  return (
    <div className="mt-14 max-md:mt-10">
      <h4 className="text-xs tracking-tight text-gray-900">
        Follow us on social media:
      </h4>
      <div className="flex gap-1 mt-3.5">
        {socialIcons.map((icon, index) => (
          <a key={index} href="#" aria-label={`Follow us on ${icon.alt}`}>
            <img 
              loading="lazy" 
              src={icon.src} 
              alt={icon.alt}
              className="object-contain shrink-0 w-9 rounded-md aspect-square" 
            />
          </a>
        ))}
      </div>
    </div>
  );
}

export default SocialMedia;